version: '3'
services:
  distill:
    tty: true
    build: ./distill
    ports:
      - "8081:8081"
    volumes:
      - ./distill:/app/distill
    command: uvicorn distill.main:app --reload --host 0.0.0.0 --port 8081
